### ISSUE TITLE
Would you agree with F-Droid store inclusion?

### ISSUE THREAD

**Issue by revuwa** [5GSD/AIMSICDL#2]
Thanks a lot for the revival and all your enthusiasm!

The "AIMSICD" was included in the F-Droid store:
* https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues/3
* https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues/156

Would you agree with the inclusion of AIMSICDL, too?

The requests for packaging is opened already: https://gitlab.com/fdroid/rfp/issues/215

**Comment by emigenix** [comment]
@revuwa Yes, of course F-droid would eventually be good, but **not now**.  The reason is that the app simply doesn't work in it's current state. None of the detections work as of today. We're rebuilding the app from bottom up, and using the parts that do work. So until more developers come forward and show interest, I'm afraid there will be no F-droid or any other availability any time soon. Also GSM is rapidly going out of fashion, so detection need to have to have full LTE support to be of any use.
